name: ARM64 Server Build

on: [push, pull_request]

jobs:
  build_server_arm64:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Disable git automatic line ending conversion
      run: git config --global core.autocrlf false

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ cmake ninja-build pkg-config nlohmann-json3-dev libncurses-dev libglew-dev
        sudo apt-get install -y libasound2-dev libjack-jackd2-dev ladspa-sdk libcurl4-openssl-dev libfreetype-dev libfontconfig1-dev
        sudo apt-get install -y libx11-dev libxcomposite-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libglu1-mesa-dev mesa-common-dev

    - name: Build Flatbuffers
      run: |
        cmake -S third_party/flatbuffers -B third_party/flatbuffers/LinuxBuilds -G Ninja -DCMAKE_BUILD_TYPE=Release
        cmake --build third_party/flatbuffers/LinuxBuilds --parallel

    - name: Build JammerNetzServer
      run: |
        cmake -S . -B builds-arm64-server -G Ninja -DCMAKE_BUILD_TYPE=Release -DBUILD_JAMMERNETZ_CLIENT=OFF -DJAMMERNETZ_ENABLE_LTO=ON -DCMAKE_POLICY_VERSION_MINIMUM=3.5
        cmake --build builds-arm64-server --target JammerNetzServer --parallel

    - name: Upload ARM64 Server Artifact
      uses: actions/upload-artifact@v4
      with:
        name: JammerNetzServer-arm64
        path: builds-arm64-server/Server/JammerNetzServer
